server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: qeDuv5dLtGXOaZOcWhtElpDLlbh6fWyy
            client-secret: _Bp0UGoUrgFvH8HKmdD3x01fmIcwMNwQ60eDFC_YkUamb8yviY8_klxefEkXRz0O
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/okta"
            client-name: Okta
            authorization-grant-type: authorization_code
            logout-redirect: http://localhost:4200
        provider:
          okta:
            authorization-uri: https://dev-e8vigvs7hi8lgvvj.us.auth0.com/authorize
            token-uri: https://dev-e8vigvs7hi8lgvvj.us.auth0.com/oauth/token
            user-info-uri: https://dev-e8vigvs7hi8lgvvj.us.auth0.com/userinfo
            user-info-attribute: name
            jwk-set-uri: https://dev-e8vigvs7hi8lgvvj.us.auth0.com/.well-known/jwks.json
        resourceserver:
          jwt:
            issuer-uri: https://dev-e8vigvs7hi8lgvvj.us.auth0.com